/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2015-12-06 23:39:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.supinfo.suptravel.dao.UserDAO;
import com.supinfo.suptravel.dao.TripDAO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.supinfo.suptravel.dao.TripDAO");
    _jspx_imports_classes.add("com.supinfo.suptravel.dao.UserDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-16");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-16\">\n");
      out.write("\t\t<title>SupTravel :: Welcome</title>\n");
      out.write("\t\t<link rel='icon' href='favicon.ico' />\n");
      out.write("    \t<link rel='icon' type='image/gif' href='cactusgreen.gif' />\n");
      out.write("   \t\t <!-- loading CSS -->\n");
      out.write("    \t<link href='./css/stylesheets/style.css' rel='stylesheet'>\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t\t<header>\n");
      out.write("\t\t\t<div class=\"banner\">\n");
      out.write("\t\t\t\t<div class=\"logo\"></div>\n");
      out.write("\t\t\t\t<div class=\"titles\">\n");
      out.write("\t\t\t\t\t<h1>SupTravel</h1>\n");
      out.write("\t\t\t\t\t<h2>Trouver votre voyage, depuis votre campus.</h2>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"connectic\">\n");
      out.write("\t\t\t\t\t<span>login</span>\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"Login\">\n");
      out.write("\t\t\t\t\t\t<label>\n");
      out.write("\t\t\t\t\t\t\t<span> User :</span>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" />\n");
      out.write("\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t<label>\n");
      out.write("\t\t\t\t\t\t\t<span> Password :</span>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"password\" />\n");
      out.write("\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"OK\"/>\n");
      out.write("\t\t\t\t\t\t<button>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"register.jsp\">Register</a>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</header>\n");
      out.write("\t\t<div class=\"main\">\n");
      out.write("\t\t\t<span>You are not log in the application. Plase log in or register to enjoy this app.</span>\n");
      out.write("\t\t\t<div class=\"stats\">\n");
      out.write("\t\t\t\t<span>\n");
      out.write("\t\t\t\t\tNumber of register users\n");
      out.write("\t\t\t\t</span>\n");
      out.write("\t\t\t\t<span>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t");
 	UserDAO u = new UserDAO();
						Long nu = u.getNumberUser();
						out.println (nu); 
      out.write("\n");
      out.write("\t\t\t\t</span>\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<span>Number of trips available</span>\n");
      out.write("\t\t\t\t\t<span>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t");
 	TripDAO t = new TripDAO();
						Long tu = t.getNumberTrip();
						out.println (tu); 
      out.write("\n");
      out.write("\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
